// dash_solid/src/components/modal/Modal.tsx
import styles from './Modal.module.css';
import { Portal } from 'solid-js/web';
import { onCleanup, type ParentComponent } from 'solid-js';

interface Props {
  title: string;
  onClose: () => void;
}

const Modal: ParentComponent<Props> = props => {
  let modalDiv!: HTMLDivElement;

  const handleClickOutside = (e: MouseEvent) => {
    if (modalDiv && !modalDiv.contains(e.target as Node)) {
      props.onClose();
    }
  };
  document.addEventListener('mousedown', handleClickOutside);

  onCleanup(() => {
    document.removeEventListener('mousedown', handleClickOutside);
  });

  return (
    <Portal>
      <div class={styles.overlay}>
        <div ref={modalDiv} class={styles.modal}>
          <h2 class={styles.title}>{props.title}</h2>
          {props.children}
        </div>
      </div>
    </Portal>
  );
};

export { Modal };

// dash/src/components/modal/Modal.tsx
import {type ReactNode, useEffect, useRef} from "react";
import styles from './Modal.module.css'

interface Props {
    title: string;
    onClose: () => void;
    children: ReactNode;
}

function Modal({title, onClose, children}: Props) {
    const ref = useRef<HTMLDivElement>(null);

    useEffect(() => {
        const handleClickOutside = (e: MouseEvent) => {
            ref.current && !ref.current.contains(e.target as Node) && onClose();
        }
        document.addEventListener("mousedown", handleClickOutside);
        return () => document.removeEventListener("mousedown", handleClickOutside);
    }, [onClose]);

    return (
        <div className={styles.overlay}>
            <div ref={ref} className={styles.modal}>
                <h2 className={styles.title}>{title}</h2>
                {children}
            </div>
        </div>
    );
}

export {Modal}
