// dash/src/components/pages/notes/elements/contextmenu/SettingsContextMenu.tsx
import { ContextMenu } from '../../../../shared/contextmenu/ContextMenu.tsx';
import { type Component, createEffect } from 'solid-js';
import { createMutable } from 'solid-js/store';
import { useApp } from '../../../../../app/appContext.tsx';

interface Props {
  x: number;
  y: number;
  onClose: () => void;
}

const SettingsContextMenu: Component<Props> = props => {
  const app = useApp();
  const state = createMutable({
    x: props.x,
    y: props.y,
  });
  const menuHeight = 24;

  createEffect(() => {
    state.x = props.x;
    state.y = props.y - menuHeight < 0 ? props.y : props.y - menuHeight;
  });

  const handleLogout = async () => {
    await app.auth.logout();
    app.resetState();
  };

  return (
    <ContextMenu x={state.x} y={state.y} onClose={props.onClose}>
      <button onClick={handleLogout}>Log out</button>
    </ContextMenu>
  );
};

export { SettingsContextMenu };

// dash/src/components/contextmenu/SettingsContextMenu.tsx
import {ContextMenu} from "./ContextMenu.tsx";
import {useAuth} from "../../context/AuthContext.tsx";
import {useRouter} from "@tanstack/react-router";
import {useLayoutEffect, useState} from "react";

interface Props {
    x: number;
    y: number;
    onClose: () => void;
}

function SettingsContextMenu({x, y, onClose}: Props) {
    const auth = useAuth()
    const router = useRouter()
    const [pos, setPos] = useState({x, y});

    useLayoutEffect(() => {
        const menuHeight = 24;
        const adjustedY = y - menuHeight < 0 ? y : y - menuHeight;
        setPos({x, y: adjustedY});
    }, [x, y]);

    const handleLogout = () => {
        auth.logout().then(() => {
            router.invalidate()
        })
    };
    return (
        <ContextMenu x={pos.x} y={pos.y} onClose={onClose}>
            <button onClick={handleLogout}>Logout</button>
        </ContextMenu>
    );
}

export {SettingsContextMenu}
