// dash/src/components/elements/Sidebar.tsx
import { A } from '@solidjs/router';
import styles from './Sidebar.module.css';
import { createMutable } from 'solid-js/store';
import { type Component, For, Show } from 'solid-js';
import type { Project } from '../../app/types/project.ts';
import { SettingsContextMenu } from '../contextmenu/SettingsContextMenu.tsx';
import { ProjectContextMenu } from '../contextmenu/ProjectContextMenu.tsx';
import { SidebarContextMenu } from '../contextmenu/SidebarContextMenu.tsx';
import { useApp } from '../../app/appContext.tsx';

type ContextMenuState = 'Closed' | 'Sidebar' | 'Settings' | 'Project';

interface Props {
  openAddModal: () => void;
  openEditModal: (project: Project | null) => void;
}

const Sidebar: Component<Props> = props => {
  const app = useApp();
  const state = createMutable({
    contextMenu: {
      state: 'Closed' as ContextMenuState,
      pos: { x: 0, y: 0 },
      project: null as Project | null,
    },
  });

  const setContextMenu = (
    e: MouseEvent,
    contextMenuState: ContextMenuState,
    project: Project | null = null
  ) => {
    e.preventDefault();
    e.stopPropagation();
    state.contextMenu.state = contextMenuState;
    state.contextMenu.pos = { x: e.clientX, y: e.clientY };
    state.contextMenu.project = project;
  };

  const closeMenus = () => {
    state.contextMenu.state = 'Closed';
  };

  const openAddModal = () => {
    props.openAddModal();
    closeMenus();
  };

  const openEditModal = () => {
    props.openEditModal(state.contextMenu.project);
    closeMenus();
  };

  return (
    <>
      <div
        class={styles.wrapper}
        onContextMenu={e => setContextMenu(e, 'Sidebar')}
        data-testid="sidebar"
      >
        <ul>
          <For each={app.notes.getProjects()}>
            {project => (
              <li onContextMenu={e => setContextMenu(e, 'Project', project)}>
                <A href={`/notes/${project.slug}`}>{project.title}</A>
              </li>
            )}
          </For>
        </ul>
        <div>
          <div class={styles.settings} onClick={e => setContextMenu(e, 'Settings')}>
            ☰
          </div>
        </div>
        <Show when={state.contextMenu.state === 'Settings'}>
          <SettingsContextMenu
            x={state.contextMenu.pos.x}
            y={state.contextMenu.pos.y}
            onClose={closeMenus}
          />
        </Show>
        <Show when={state.contextMenu.state === 'Project'}>
          <ProjectContextMenu
            x={state.contextMenu.pos.x}
            y={state.contextMenu.pos.y}
            onEdit={openEditModal}
            onClose={closeMenus}
          />
        </Show>
        <Show when={state.contextMenu.state === 'Sidebar'}>
          <SidebarContextMenu
            x={state.contextMenu.pos.x}
            y={state.contextMenu.pos.y}
            onAdd={openAddModal}
            onClose={closeMenus}
          />
        </Show>
      </div>
    </>
  );
};

export { Sidebar };

// dash/src/components/Sidebar.tsx
import {LogoutButton} from "./LogoutButton.tsx";
import {Link, useLoaderData} from "@tanstack/react-router";
import {useQuery, useQueryClient} from "@tanstack/react-query";
import {getProjectList} from "../api/project.tsx";
import type {Project} from "../types/project.ts";
import * as React from "react";
import {useState} from "react";
import {EditProjectModal} from "./modal/EditProjectModal.tsx";
import {AddProjectModal} from "./modal/AddProjectModal.tsx";
import {ProjectContextMenu} from "./contextmenu/ProjectContextMenu.tsx";
import {SidebarContextMenu} from "./contextmenu/SidebarContextMenu.tsx";
import styles from './Sidebar.module.css'

function Sidebar() {
    const queryClient = useQueryClient();

    // weird type issue here, idk...
    const {initialProjects} = useLoaderData({from: '/_auth/notes'}) as { initialProjects: Project[] }
    const {data: projects = []} = useQuery({
        queryKey: ["projects"],
        queryFn: getProjectList,
        initialData: initialProjects
    })

    const [sidebarContextMenu, setSidebarContextMenu] = useState<{ x: number; y: number } | null>(null);
    const [projectContextMenu, setProjectContextMenu] = useState<{
        x: number;
        y: number;
        project: Project
    } | null>(null);
    const [editingProject, setEditingProject] = useState<Project | null>(null);
    const [isAddOpen, setAddOpen] = useState(false);

    const openSidebarContextMenu = (e: React.MouseEvent) => {
        e.preventDefault();
        setSidebarContextMenu({x: e.clientX, y: e.clientY});
        setProjectContextMenu(null);
    }

    const openProjectContextMenu = (e: React.MouseEvent, project: Project) => {
        e.preventDefault();
        e.stopPropagation();
        setProjectContextMenu({x: e.clientX, y: e.clientY, project});
        setSidebarContextMenu(null);
    }

    const closeMenus = () => {
        setSidebarContextMenu(null);
        setProjectContextMenu(null);
    }

    const openEditModal = (p: Project) => {
        setEditingProject(p);
        setProjectContextMenu(null);
    }

    const openAddModal = () => {
        setAddOpen(true);
        setSidebarContextMenu(null);
    }

    const closeEditModal = () => {
        setEditingProject(null);
    }

    const closeAddModal = () => {
        setAddOpen(false);
    }

    const refreshProjects = () => {
        queryClient.invalidateQueries({queryKey: ['projects']})
    }

    return (
        <>
            <div className={styles.wrapper} onContextMenu={(e) => openSidebarContextMenu(e)}>
                <ul>
                    {projects.map((p) => (
                        <li key={p.slug} onContextMenu={(e) => openProjectContextMenu(e, p)}>
                            <Link to={'/notes/$slug'} params={{slug: p.slug}}>
                                {p.title}
                            </Link>
                        </li>
                    ))}
                </ul>
                <LogoutButton/>
                {projectContextMenu && (
                    <ProjectContextMenu
                        x={projectContextMenu.x}
                        y={projectContextMenu.y}
                        onEdit={() => openEditModal(projectContextMenu.project)}
                        onClose={closeMenus}
                    />
                )}
                {sidebarContextMenu && (
                    <SidebarContextMenu
                        x={sidebarContextMenu.x}
                        y={sidebarContextMenu.y}
                        onAdd={openAddModal}
                        onClose={closeMenus}
                    />
                )}
            </div>
            {editingProject && (
                <EditProjectModal project={editingProject} onClose={closeEditModal} onSuccess={refreshProjects}/>
            )}
            {isAddOpen && (
                <AddProjectModal onClose={closeAddModal} onSuccess={refreshProjects}/>
            )}
        </>
    );
}

export {Sidebar};
